Attach MenuUI choicesBtn with scripts / start designing PlayerManager
wcgary0608/Prototype02 pull request #3
Opened 2018-11-21 14:19 UTC by jxue1012

2018-11-21 14:22 UTC, jxue1012 commented
我发现，为啥还是有些莫名奇妙的文件出现在difference列表里叻!

2018-11-21 14:25 UTC, jxue1012 commented
你看看我PlayerManager.cs里那样去UPDATE Variable可以吗？不敢写太多，怕回头不太合适的话要改很多哈哈哈

2018-11-23 16:29 UTC, wcgary0608 commented on Prototype/Assets/Scripts/MainScene/MainSceneTreeNodeManager.cs
> +                localSuccess = SwitchBuffDescription(inputParams);
我们得check一下inputParams的格式再传进去。或者在switchbuffdescription 里check一下这个input是正确的格式再用

2018-11-23 16:32 UTC, wcgary0608 commented on Prototype/Assets/Scripts/MainScene/MainSceneTreeNodeManager.cs
>      private SceneStateController m_SceneController;
naming convention

2018-11-23 16:36 UTC, wcgary0608 requested changes

2018-11-23 16:36 UTC, wcgary0608 commented on Prototype/Assets/Scripts/MainScene/MainSceneTreeNodeManager.cs
> +        _uiStatusMenu.SetTextForStatusMenu(TextInStatusMenu.shenFaValue, shenFaValue.ToString());
我们能把enum也做个naming covention么？所有的enum都以enum结尾。 比如这个就TextInStatusMenuEnum

2018-11-24 01:23 UTC, jxue1012 commented on Prototype/Assets/Scripts/MainScene/MainSceneTreeNodeManager.cs
> +                localSuccess = SwitchBuffDescription(inputParams);
这个要怎么check? typeof吗？我以为inputParam只能是string欸

2018-11-24 13:31 UTC, jxue1012 commented on Prototype/Assets/Scripts/MainScene/MainSceneTreeNodeManager.cs
> +        _uiStatusMenu.SetTextForStatusMenu(TextInStatusMenu.shenFaValue, shenFaValue.ToString());
已改

2018-11-24 13:32 UTC, jxue1012 commented on Prototype/Assets/Scripts/MainScene/MainSceneTreeNodeManager.cs
> +        _uiStatusMenu.SetTextForStatusMenu(TextInStatusMenu.shenFaValue, shenFaValue.ToString());
已改

2018-11-24 13:33 UTC, jxue1012 commented on Prototype/Assets/Scripts/MainScene/MainSceneTreeNodeManager.cs
>      private SceneStateController m_SceneController;
我是看到了就改

2018-11-28 06:12 UTC, wcgary0608 commented on Prototype/Assets/Scripts/MainScene/MainSceneTreeNodeManager.cs
> +                localSuccess = SwitchBuffDescription(inputParams);
buff description如果可以是任何string 就不check了 如果只能是specific的strings，那就得check或者 switchbuffdescription 里面加一个defaultstatement

2018-11-28 06:12 UTC, wcgary0608 approved these changes

2018-11-28 06:47 UTC, wcgary0608 requested changes

2018-11-28 06:47 UTC, wcgary0608 commented on Prototype/Assets/Scripts/MainScene/SubManagers/PlayerManager/PlayerManager.cs
> +        if (_curMP == 0)
所有的if 后面 记得加 {} 大括号哦

2018-11-28 06:47 UTC, wcgary0608 commented on Prototype/Assets/Scripts/MainScene/SubManagers/PlayerManager/PlayerManager.cs
> +            tempCurMp = _maxMP;
这里也是 好几个地方都是 if 记得加括号，除非直接return 就不加， return跟if写一行

2018-11-28 06:47 UTC, wcgary0608 commented on Prototype/Assets/Scripts/MainScene/SubManagers/PlayerManager/PlayerManager.cs
> +    public int GetMaxHp()
1. 写一个player class
2. 在里面的initializer里initialize 所有的variable （这样以后写村储class的时候好用）
3. 所有的 类似于这个“GetMaxHp”的function 相当于是 get read -only property 的类别，全部用 get 来写：
        比如这样
            public int GetMaxHp
           {
                   get { return _maxHP; }
            }

4. 如果是可以read and write的， 比如curHp 就写get set 就好了
 public int GetSetCurHp
 {
       get { return _curHp; }
       set
     {
      ...set logic here...
      }
}
如果没有 set logic， 直接用 shorthand 就好了， 见下面的reference

5. 然后player manager 里面去掉这些get set的函数。这违反了law of inheritance。 直接写一个get player object。 其他的class拿了这个player object 出来再那里用就好了

Reference：
**Public field:**
public string CarNickname;

**Full Property:**
private string _carNickname;
public string CarNickname
{
get { return _carNickName; }
set { _carNickname = value; }
}


**Shorthand:**
public string CarNickname { get; set; }
 Auto-implements the private field

2018-11-28 07:06 UTC, jxue1012 commented on Prototype/Assets/Scripts/MainScene/SubManagers/PlayerManager/PlayerManager.cs
> +    public int GetMaxHp()
收到！

2018-11-28 13:12 UTC, jxue1012 commented on Prototype/Assets/Scripts/MainScene/SubManagers/PlayerManager/PlayerManager.cs
> +    public int GetMaxHp()
这个改了！你看看噢！

2018-11-28 13:12 UTC, jxue1012 commented on Prototype/Assets/Scripts/MainScene/SubManagers/PlayerManager/PlayerManager.cs
> +            tempCurMp = _maxMP;
这个，我看到的就顺手改了！

2018-11-28 13:14 UTC, jxue1012 commented on Prototype/Assets/Scripts/MainScene/MainSceneTreeNodeManager.cs
> +                localSuccess = SwitchBuffDescription(inputParams);
不是很明白？buff description这种应该是从数据表里拉出来的！

2018-11-29 02:52 UTC, wcgary0608 commented on Prototype/Assets/Scripts/MainScene/MainSceneTreeNodeManager.cs
> +                localSuccess = SwitchBuffDescription(inputParams);
这个先不管了先。。。

2018-11-29 02:53 UTC, wcgary0608 approved these changes

2018-11-29 02:53 UTC, merged